✨ Add new colors
paralenz/ui-utils pull request #18
Opened 2021-11-19 11:06 UTC by nikolajbech

2021-11-19 11:37 UTC, theill requested changes

2021-11-19 11:37 UTC, theill commented on src/colors.ts
> +  sessionOrange: '#ffc116',
I don't think the name should be "sessionOrange". We want to have colors such as "crabRed" not because it may be a red-ish color as a crab but because that's what our brand guidelines names it.

Instead of sessionOrange we would use something like "selectedSession" or "sessionDot" or whatever indicating where it is used. Similar to "rentalStateAvailable" which indicates an available rental .. not naming it something like "rentalStateRatherWhite"

2021-11-19 11:37 UTC, theill commented on src/colors.ts
> +  destroy: '#e74c3c',
I'm ok with "destroy" as a name but consider if it would make sense to name it a little bit less generic such as "destroyActionItem" or similar. Why is that less generic? It's less generic because you may want to have a "destroySession", "destroyUser", etc.

2021-11-19 11:55 UTC, nikolajbech commented on src/colors.ts
> +  destroy: '#e74c3c',
But i would like it to be more generic

2021-11-19 11:58 UTC, theill approved these changes

2021-11-19 11:58 UTC, merged

2021-11-22 06:36 UTC, arelstone commented on src/colors.ts
> +  destroy: '#e74c3c',
I agree with @nikolajbech. Colors hames in this package should be generic